server:
  port: 8080
  max-http-header-size: 65536
  tomcat:
    max-http-post-size: 10485760
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/bar?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    properties:
      hibernate.show_sql: false
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 1000Mb
  mail:
    host: smtp.qq.com
    username: hekin00@qq.com
    password: emwjhihcnoumbijb
    default-encoding: utf-8
    port: 465
    properties:
      mail.smtp.auth: true
      mail.smtp.timeout: 25000
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      smtp.socketFactory.port: 465
logging:
  level:
    root: info
    org.springframework.web: error
    org.hibernate: error
    org.JPA: error
    org.hibernate.SQL: error
file.root.path: d:/gm/uploaded_file/
img.root.path: d:/gm/uploaded_img/
