server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/backend?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    properties:
      hibernate.show_sql: false
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.qq.com
    username: hekin00@qq.com
    password: emwjhihcnoumbijb
    default-encoding: utf-8
    port: 465
    properties:
      mail.smtp.auth: true
      mail.smtp.timeout: 25000
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      smtp.socketFactory.port: 465
file.root.path: d:/gm/uploaded_file/
img.root.path: d:/gm/uploaded_img/